FROM python:3.7-stretch

RUN apt-get -y update && apt-get -y upgrade && apt-get -y install git

RUN mkdir src
RUN git clone https://github.com/onsplatform/domain_reader.git /src

WORKDIR src
RUN pip install pipenv
RUN pipenv install --dev --system --deploy 

EXPOSE 80

CMD celery -A domain.writer.import_task worker --loglevel=info